declare module "fastify/lib/symbols.js" {
  const keys = {
    kAvvioBoot: Symbol("fastify.avvioBoot"),
    kBodyLimit: Symbol("fastify.bodyLimit"),
    kChildren: Symbol("fastify.children"),
    kContentTypeParser: Symbol("fastify.contentTypeParser"),
    kDisableRequestLogging: Symbol("fastify.disableRequestLogging"),
    kGenReqId: Symbol("fastify.genReqId"),
    kHooks: Symbol("fastify.hooks"),
    kHttp2ServerSessions: Symbol("fastify.http2ServerSessions"),
    kLogLevel: Symbol("fastify.logLevel"),
    kLogSerializers: Symbol("fastify.logSerializers"),
    kOptions: Symbol("fastify.options"),
    kPluginNameChain: Symbol("fastify.pluginNameChain"),
    kRouteContext: Symbol("fastify.context"),
    kRoutePrefix: Symbol("fastify.routePrefix"),
    kServerBindings: Symbol("fastify.serverBindings"),
    kState: Symbol("fastify.state"),
    kSupportedHTTPMethods: Symbol("fastify.acceptedHTTPMethods"),
    // Schema
    kSchemaBody: Symbol("body-schema"),
    kSchemaController: Symbol("fastify.schemaController"),
    kSchemaErrorFormatter: Symbol("fastify.schemaErrorFormatter"),
    kSchemaHeaders: Symbol("headers-schema"),
    kSchemaParams: Symbol("params-schema"),
    kSchemaQuerystring: Symbol("querystring-schema"),
    kSchemaResponse: Symbol("response-schema"),
    kSchemaVisited: Symbol("fastify.schemas.visited"),
    // Request
    kHandlerTimeout: Symbol("fastify.handlerTimeout"),
    kOnAbort: Symbol("fastify.request.onAbort"),
    kRequest: Symbol("fastify.Request"),
    kRequestAcceptVersion: Symbol("fastify.RequestAcceptVersion"),
    kRequestCacheValidateFns: Symbol("fastify.request.cache.validateFns"),
    kRequestOriginalUrl: Symbol("fastify.request.originalUrl"),
    kRequestPayloadStream: Symbol("fastify.RequestPayloadStream"),
    kRequestSignal: Symbol("fastify.request.signal"),
    kTimeoutTimer: Symbol("fastify.request.timeoutTimer"),
    // 404
    kCanSetNotFoundHandler: Symbol("fastify.canSetNotFoundHandler"),
    kDefaultJsonParse: Symbol("fastify.defaultJSONParse"),
    kFourOhFour: Symbol("fastify.404"),
    kFourOhFourContext: Symbol("fastify.404ContextKey"),
    kFourOhFourLevelInstance: Symbol("fastify.404LogLevelInstance"),
    // Reply
    kReply: Symbol("fastify.Reply"),
    kReplyCacheSerializeFns: Symbol("fastify.reply.cache.serializeFns"),
    kReplyEndTime: Symbol("fastify.reply.endTime"),
    kReplyErrorHandlerCalled: Symbol("fastify.reply.errorHandlerCalled"),
    kReplyHasStatusCode: Symbol("fastify.reply.hasStatusCode"),
    kReplyHeaders: Symbol("fastify.reply.headers"),
    kReplyHijacked: Symbol("fastify.reply.hijacked"),
    kReplyIsError: Symbol("fastify.reply.isError"),
    kReplyIsRunningOnErrorHook: Symbol("fastify.reply.isRunningOnErrorHook"),
    kReplyNextErrorHandler: Symbol("fastify.reply.nextErrorHandler"),
    kReplySerializer: Symbol("fastify.reply.serializer"),
    kReplySerializerDefault: Symbol("fastify.replySerializerDefault"),
    kReplyStartTime: Symbol("fastify.reply.startTime"),
    kReplyTrailers: Symbol("fastify.reply.trailers"),
    // This symbol is only meant to be used for fastify tests and should not be used for any other purpose
    kChildLoggerFactory: Symbol("fastify.childLoggerFactory"),
    kErrorHandler: Symbol("fastify.errorHandler"),
    kErrorHandlerAlreadySet: Symbol("fastify.errorHandlerAlreadySet"),
    kHasBeenDecorated: Symbol("fastify.hasBeenDecorated"),
    kKeepAliveConnections: Symbol("fastify.keepAliveConnections"),
    kRouteByFastify: Symbol("fastify.routeByFastify"),
    kTestInternals: Symbol("fastify.testInternals")
  };

  export default keys;
}
